### ISSUE TITLE
destination directory not removed

### ISSUE THREAD

**Issue by dkebler** [blittle/bower-installer#102]
according to your list of updates as of 0.8.0 the destination directory should not be repeated unless I use the -k switch.   That is not the case.  (eg saves  ./jquery/jquery.js  when I want just ./jquery.js)

I am running 1.2.0  

-----------

0.8.0 - Add an option for not removing the destination directories (--keep or -k). Preserve folder structures per extensions issue #52

**Comment by blittle** [comment]
This was changed in version 1.0.0 - By efault the installation directory is not removed in 1.0.0 and onward. If you want it to be removed before installation, use the flag `--remove-install-path` or `-p`

**Comment by dkebler** [comment]
Neither of those two flags worked.  It's still outputing a copy of directory from which file came.
Assuming I can get this to work does BI have a json file of defaults so I can set this permenently.

version switch is always very nice in any cli program.  But I found this digging at npm site
npm list -g --depth=0

my json file install entry
  "install" : {
    "path" : {
      "css": "../static/framework/css",
      "js": "../static/framework/js"
    	}
	}


Thx BTW.   After getting stuck using symbolic links BI was just what I needed.

**Comment by blittle** [comment]
Can you post your whole bower file?

**Comment by dkebler** [comment]
here is bower.json from root of project
```
{
  "name": "hugo-foundation-compass-app",
  "version": "0.0.1",
  "private": "true",
  "dependencies": {
    "foundation": "zurb/bower-foundation"
  },
  "install" : {
    "path" : {
      "css": "../static/framework/css",
      "js": "../static/framework/js"
    	}
	}
}
```
here is bower.json from one of the installed packages which copies as ./static/framework/js/jquery/jquery.js instead of  ./static/framework/js/jquery.js  when using --remove-install-path
```
{
  "name": "jquery",
  "version": "2.1.3",
  "main": "dist/jquery.js",
  "license": "MIT",
  "ignore": [
    "**/.*",
    "build",
    "speed",
    "test",
    "*.md",
    "AUTHORS.txt",
    "Gruntfile.js",
    "package.json"
  ],
  "devDependencies": {
    "sizzle": "2.1.1-jquery.2.1.2",
    "requirejs": "2.1.10",
    "qunit": "1.14.0",
    "sinon": "1.8.1"
  },
  "keywords": [
    "jquery",
    "javascript",
    "library"
  ]
}
```

output from bower-installer running on mint17.1/ubuntu14.1
```
$ bower-installer --remove-install-path
Setting up install paths...Finished
Running bower install...Finished
Installing: 
	fastclick : /mnt/AllData/DGK/hacking/hugosites/testsite/framework/../static/framework/js/fastclick/fastclick.js
	jquery-placeholder : /mnt/AllData/DGK/hacking/hugosites/testsite/framework/../static/framework/js/jquery-placeholder/jquery.placeholder.js
	jquery.cookie : /mnt/AllData/DGK/hacking/hugosites/testsite/framework/../static/framework/js/jquery.cookie/jquery.cookie.js
	foundation : /mnt/AllData/DGK/hacking/hugosites/testsite/framework/../static/framework/css/foundation/foundation.css
	foundation : /mnt/AllData/DGK/hacking/hugosites/testsite/framework/foundation.css.map
	foundation : /mnt/AllData/DGK/hacking/hugosites/testsite/framework/../static/framework/js/foundation/foundation.js
	jquery : /mnt/AllData/DGK/hacking/hugosites/testsite/framework/../static/framework/js/jquery/jquery.js
Success
```
 
-----version
```
$ npm list -g --depth=0
/usr/local/lib
├── bower@1.3.9
├── bower-installer@1.2.0
├── grunt-cli@0.1.13
└── npm@1.4.28
```
__I see in the BI package directory some tests.  Anything of those worth running to help track down the issue?

**Comment by dkebler** [comment]
I see you closed this.  Any thoughts on why this switch does not work for me?  I can live with it, not the end of the world having to put in the extra directory in the path,  just annoying and potentiall a source of error.

**Comment by joseluis** [comment]
This switch didn't work for me either. I only got it working again after removing the "path" attribute. Seems like another bug.
