### ISSUE TITLE
First Impressions

### ISSUE THREAD

**Issue by heyallan** [blittle/bower-installer#108]
So, in addition to /bower_components, I get (yet) another folder but with streamlined componentes… Is that correct? I was hoping to eliminate /bower_components with src files automatically, but they're still there.

I'm confused. I'd appreciate any help.

**Comment by RQuadling** [comment]
Step 1. ```bower-installer --help```
Step 2. ```bower-installer -pr```
Step 3. There is no step 3.

**Comment by blittle** [comment]
Underneath bower-installer is just using bower, so the bower_components directory is still necessary. Just add it to your git ignore file and you shouldn't need to worry about it.

**Comment by heyallan** [comment]
@RQuadling Very helpful answer. It provided me valuable orientation. Thanks.
@blittle Not what I needed, but thanks anyway.

(We) beginners would appreciate having this in the README.md, or Wiki:
```
-r --remove
-p --remove-install-path
-h --help
```
