### ISSUE TITLE
bower-installer is not copying multiple files

### ISSUE THREAD

**Issue by hayesmaker** [blittle/bower-installer#123]
"sources": {
      "blanket": [
        "bower_components/blanket/src/blanket_browser.js",
        "bower_components/blanket/src/adaptors/mocha-blanket.js"
      ],
     }

only blanket_browser.js is copied to my vendor folder.

**Comment by rquadling** [comment]
Typo.

adapt E rs

**Comment by hayesmaker** [comment]
oopsie,, lol
