### ISSUE TITLE
Don't create folder with package name

### ISSUE THREAD

**Issue by tikoflano** [blittle/bower-installer#139]
I've been trying to add jquery.js and bootstrap.css into my project. I would like to have this files exactly in:

* src/js/jquery.js
* src/css/bootstrap.css

Right now there is no way to do this because bower-installer will always create a folder with the package name si this would became

* src/js/jquery/jquery.js
* src/css/bootstrap/bootstrap.css

The closest I have get is using the "mapping" option (with the target name starting with "../", eg "../jquery.js") which creates the files in the desired locations but keeps an empty folder with the package name.

**Comment by liudonghua123** [comment]
I have faced the same problem.

**Comment by liudonghua123** [comment]
I replaced the latest code on `/usr/local/lib/node_modules/bower-installer` and modifed
```
var defaultInstallOptions = {
  "includePackageNameInInstallPath": false
};
```
in `lib/installer.js` file. Then I got expected result.

**Comment by liudonghua123** [comment]
As https://github.com/blittle/bower-installer/pull/128 pointed, a more elegant way is provide this piece of code
```
    "options" : {
      "includePackageNameInInstallPath": false
    }
```
in your install block of `bower.json` file.

**Comment by tikoflano** [comment]
Thank you very much!

**Comment by derekoakley** [comment]
@tikoflano @liudonghua123 I downloaded the latest master and copied it over the version in `/usr/local/lib/node_modules/bower-installer` and tried adding the options key and even editing the `lib/installer.js` though neither works.

Here's my bower.json file:
```
{
  "name" : "test",
  "version": "0.1",
  "dependencies": {
    "medium-editor": "latest"
  },
  "install": {
    "options": {"includePackageNameInInstallPath": "false"},
    "path": "mallowstreet/assets/js",
    "sources": {
      "medium-editor": {
        "mapping": {"bower_components/medium-editor/dist/js/medium-editor.min.js": "medium-editor.min.js"}
      }
    }
  }
}
```
Any ideas?

**Comment by Manidos** [comment]
@derekoakley, have you solved this problem?

**Comment by derekoakley** [comment]
Sorry @Manidos, unfortunately I don't use bower anymore. I think I used a node module to copy the files in the end.
