### ISSUE TITLE
util.pump() deprecated 

### ISSUE THREAD

**Issue by knownasilya** [blittle/bower-installer#20]
Using `Node 0.10.13` and `Bower 1.0.0`, and get this message:

> util.pump() is deprecated. Use readableStream.pipe() instead.

**Comment by g105b** [comment]
Can't reproduce this. [No mention of `.pump`](https://github.com/blittle/bower-installer/search?utf8=%E2%9C%93&q=.pump&type=Code) within the repo, can I close?

**Comment by knownasilya** [comment]
Sure :+1:
