### ISSUE TITLE
Support for installing to specific path according to file extension and filename

### ISSUE THREAD

**Issue by g105b** [blittle/bower-installer#84]
Currently, files can be configured to install to specific directories within a project, but this is limited to the file extension.

I would like to be able to do this:

```json
{
	"name": "my-project",
	"install": {
		"path": {
			"css": "src/Style/Lib",
			"font.css": "src/Asset/Font",
			"woff2": "src/Asset/Font"
		}
	}
}
```

In the above example, `.css` files would be installed to the `src/Style/Lib` directory, but files that ended with `.font.css` would be installed to the `src/Asset/Font` directory.

I have also tried using a glob-like approach: `"*/.font.css": "src/Asset/Font"`

**Comment by blittle** [comment]
Closed with https://github.com/blittle/bower-installer/pull/101
